export type { OCRRuntimePort } from "./ocr-runtime-port";

export type {
  CanonicalOCRCapabilities,
  CanonicalOCRConfiguration,
  CanonicalOCRIdentity,
  CanonicalOCRMetadata,
  CanonicalOCRProvider,
  CanonicalOCRProviderReference,
  CanonicalOCRProviderReferenceId,
  CanonicalOCRReference,
  CanonicalOCRRequest,
  CanonicalOCRResult,
  CanonicalOCRSession,
  CanonicalOCRStatistics,
  CanonicalOCROperation,
  CloseOCRJobInput,
  CloseOCRJobResult,
  CoordinateOCRInput,
  CoordinateOCRResult,
  GetOCRResultInput,
  GetOCRResultResult,
  GetOCRRuntimeSessionInput,
  GetOCRRuntimeSessionResult,
  ListOCRProviderReferencesResult,
  ListOCRRuntimeSessionsInput,
  ListOCRRuntimeSessionsResult,
  OCRCapabilities,
  OCRConfidence,
  OCRDocument,
  OCREngine,
  OCRHealth,
  OCRJob,
  OCRLanguage,
  OCRMetadata,
  OCRPage,
  OCRProcessingContext,
  OCRRequest,
  OCRResult,
  OCRRuntimeCapabilities,
  OCRRuntimeEngineCapabilities,
  OCRRuntimeEnterpriseDeps,
  OCRRuntimeHealth,
  OCRRuntimeInfo,
  OCRRuntimeOperationalControls,
  OCRRuntimeOperationEnvelope,
  OCRRuntimeOptions,
  OCRRuntimeProviderId,
  OCRRuntimeProviderMetadata,
  OCRRuntimeProviderOptions,
  OCRRuntimeRegistration,
  OCRRuntimeSessionStatus,
  OCRRuntimeStatus,
  OCRRuntimeStructuredLog,
  OCRRuntimeTelemetry,
  OCRStatsInput,
  OCRStatsResult,
  OCRStatus,
  OpenOCRJobInput,
  OpenOCRJobResult,
  ProcessOCRInput,
  ProcessOCRResult,
  RegisterOCRDocumentInput,
  RegisterOCRDocumentResult,
  SubmitOCRRequestInput,
  SubmitOCRRequestResult,
} from "./types";

export { STRUCTURAL_OCR_PROVIDER_REFERENCES, resolveStructuralProviderReference } from "./types";

export {
  DEFAULT_MOCK_OCR_RUNTIME_ENGINE_CAPABILITIES,
  DEFAULT_OCR_RUNTIME_ENGINE_CAPABILITIES,
  defineOCRRuntimeEngineCapabilities,
  emptyOCRRuntimeEngineCapabilities,
  toCanonicalOCRCapabilities,
} from "./capabilities";

export {
  OCR_RUNTIME_IDENTITY,
  createOCRCapRequestId,
  createOCRDocumentId,
  createOCRJobId,
  createOCRResultId,
  createOCRRuntimeRequestId,
  createOCRRuntimeSessionId,
  resetAllOCRRuntimeIdSequences,
  resetOCRRuntimeSessionIdSequence,
} from "./identity";
