export type { MetadataPort } from "./metadata-port";
export type {
  GetEntityInput,
  GetEntityResult,
  GetSchemaInput,
  GetSchemaResult,
  ListSchemasInput,
  ListSchemasResult,
  ListTemplatesInput,
  ListTemplatesResult,
  MetadataArtifactKind,
  MetadataAttribute,
  MetadataCapabilities,
  MetadataCategory,
  MetadataCompatibility,
  MetadataConstraint,
  MetadataConstraintKind,
  MetadataEntity,
  MetadataEnumeration,
  MetadataHealth,
  MetadataId,
  MetadataName,
  MetadataNamespace,
  MetadataProperty,
  MetadataPropertyKind,
  MetadataProviderId,
  MetadataProviderOptions,
  MetadataReference,
  MetadataRelationship,
  MetadataSchema,
  MetadataSchemaStatus,
  MetadataTag,
  MetadataTemplate,
  MetadataValidation,
  MetadataVersionInfo,
  MetadataVersionLabel,
  RegisterEntityInput,
  RegisterEntityResult,
  RegisterSchemaInput,
  RegisterSchemaResult,
  RegisterTemplateInput,
  RegisterTemplateResult,
} from "./types";

export {
  entityDeclaresInheritance,
  getDeclaredInheritanceChain,
  getEntityBaseReference,
  getSchemaBaseReference,
  schemaDeclaresInheritance,
} from "./inheritance";

export {
  METADATA_SCHEMA_STATUSES,
  createVersionInfo,
  declaresCompatibilityWith,
  declaresIncompatibilityWith,
  getSchemaStatus,
  getSchemaVersion,
  isKnownSchemaStatus,
  touchVersionInfo,
} from "./versioning";

export {
  METADATA_CONSTRAINT_KINDS,
  collectionConstraint,
  defineConstraint,
  expressionConstraint,
  isKnownConstraintKind,
  rangeConstraint,
  referenceConstraint,
  regexConstraint,
  requiredConstraint,
  uniqueConstraint,
} from "./constraints";
