export {
  H01_TISS_INTEGRATION_CAPABILITIES,
  H02_TISS_INTEGRATION_CAPABILITIES,
  H03_TISS_INTEGRATION_CAPABILITIES,
  H04_TISS_INTEGRATION_CAPABILITIES,
  H05_TISS_INTEGRATION_CAPABILITIES,
  H06_TISS_INTEGRATION_CAPABILITIES,
  H07_TISS_INTEGRATION_CAPABILITIES,
  H08_TISS_INTEGRATION_CAPABILITIES,
  H09_TISS_INTEGRATION_CAPABILITIES,
  type TISSIntegrationCapabilities,
} from "./capabilities";
