export type { XMLValidationRuntimePort } from "./xml-validation-runtime-port";

export type {
  AuditResult,
  AutoFillResult,
  CanonicalGuide,
  CanonicalMappingResult,
  CanonicalXMLValidationCapabilities,
  CanonicalXMLValidationHealth,
  CanonicalXMLValidationIssue,
  CanonicalXMLValidationMetadata,
  CanonicalXMLValidationOperation,
  CanonicalXMLValidationProfile,
  CanonicalXMLValidationReference,
  CanonicalXMLValidationRequest,
  CanonicalXMLValidationResult,
  CanonicalXMLValidationStatistics,
  CanonicalXMLValidationStatus,
  CanonicalXMLValidationSummary,
  CanonicalXMLValidationVersion,
  GetCanonicalXMLValidationResultInput,
  GetCanonicalXMLValidationResultResult,
  GetXMLValidationResultInput,
  GetXMLValidationResultResult,
  ListCanonicalXMLValidationResultsInput,
  ListCanonicalXMLValidationResultsResult,
  ListXMLValidationResultsInput,
  ListXMLValidationResultsResult,
  QualityAssessment,
  ValidateCanonicalXMLInput,
  ValidateCanonicalXMLResult,
  ValidateXMLInput,
  ValidateXMLResult,
  ValidationResult,
  XMLDocument,
  XMLValidationCapabilities,
  XMLValidationCompatibilityContract,
  XMLValidationConsistencyContract,
  XMLValidationContext,
  XMLValidationHealth,
  XMLValidationIntegrityContract,
  XMLValidationIssue,
  XMLValidationMetadata,
  XMLValidationNamespaceContract,
  XMLValidationOperation,
  XMLValidationProfile,
  XMLValidationReference,
  XMLValidationReportContract,
  XMLValidationRequest,
  XMLValidationResult,
  XMLValidationRuntimeCapabilities,
  XMLValidationRuntimeEngineCapabilities,
  XMLValidationRuntimeEnterpriseDeps,
  XMLValidationRuntimeHealth,
  XMLValidationRuntimeInfo,
  XMLValidationRuntimeOperationalControls,
  XMLValidationRuntimeOperationEnvelope,
  XMLValidationRuntimeOptions,
  XMLValidationRuntimePortCapabilities,
  XMLValidationRuntimeProviderId,
  XMLValidationRuntimeProviderMetadata,
  XMLValidationRuntimeProviderOptions,
  XMLValidationRuntimeRegistration,
  XMLValidationRuntimeStatus,
  XMLValidationRuntimeStructuredLog,
  XMLValidationRuntimeTelemetry,
  XMLValidationSchemaContract,
  XMLValidationStatistics,
  XMLValidationStatsInput,
  XMLValidationStatsResult,
  XMLValidationStatus,
  XMLValidationStructureContract,
  XMLValidationSummary,
  XMLValidationVersion,
  XMLValidationVersionContract,
  ValidateXSDInput,
  ValidateXSDResult,
  ValidateNamespaceInput,
  ValidateNamespaceResult,
  CanonicalValidationIssue,
  CanonicalValidationStatistics,
  CanonicalXSDValidationResult,
  CanonicalNamespaceValidationContext,
  CanonicalNamespaceValidationResult,
  XMLValidationRuntimeContext,
} from "./types";

export {
  DEFAULT_MOCK_XML_VALIDATION_RUNTIME_CAPABILITIES,
  DEFAULT_MOCK_XML_VALIDATION_RUNTIME_ENGINE_CAPABILITIES,
  DEFAULT_XML_VALIDATION_RUNTIME_CAPABILITIES,
  DEFAULT_XML_VALIDATION_RUNTIME_ENGINE_CAPABILITIES,
  defineXMLValidationRuntimeCapabilities,
  defineXMLValidationRuntimeEngineCapabilities,
  emptyXMLValidationRuntimeCapabilities,
  emptyXMLValidationRuntimeEngineCapabilities,
  toCanonicalXMLValidationCapabilities,
  toXMLValidationCapabilities,
} from "./capabilities";

export {
  XML_VALIDATION_RUNTIME_IDENTITY,
  createXMLValidationContextId,
  createXMLValidationId,
  createXMLValidationResultId,
  createXMLValidationRuntimeRequestId,
  resetAllXMLValidationRuntimeIdSequences,
  resetXMLValidationRuntimeIdSequences,
} from "./identity";

export {
  createDisabledXMLValidationReport,
  createDisabledXMLValidationSchema,
  createDisabledXMLValidationStructure,
} from "./canonical";
