/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TissRouteImport } from './routes/tiss'
import { Route as SiteRouteImport } from './routes/site'
import { Route as ProcessamentoRouteImport } from './routes/processamento'
import { Route as PlantoesRouteImport } from './routes/plantoes'
import { Route as PilotoRouteImport } from './routes/piloto'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OperacaoRouteImport } from './routes/operacao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LancamentoRouteImport } from './routes/lancamento'
import { Route as InstituicaoRouteImport } from './routes/instituicao'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ExecutivoRouteImport } from './routes/executivo'
import { Route as EscalasRouteImport } from './routes/escalas'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as CentralRouteImport } from './routes/central'
import { Route as CapturaRouteImport } from './routes/captura'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlantoesShiftIdRouteImport } from './routes/plantoes.$shiftId'
import { Route as LoginRedefinirSenhaRouteImport } from './routes/login.redefinir-senha'
import { Route as LoginEsqueciSenhaRouteImport } from './routes/login.esqueci-senha'
import { Route as FinanceiroFechamentoOperacionalRouteImport } from './routes/financeiro.fechamento-operacional'
import { Route as FinanceiroDashboardExecutivoRouteImport } from './routes/financeiro.dashboard-executivo'
import { Route as FinanceiroConciliacaoOperacionalRouteImport } from './routes/financeiro.conciliacao-operacional'
import { Route as Fase3SlugRouteImport } from './routes/fase3.$slug'
import { Route as ContratosRevisaoContractIdRouteImport } from './routes/contratos/revisao.$contractId'
import { Route as CapturaRevisaoSessionIdRouteImport } from './routes/captura/revisao.$sessionId'

const TissRoute = TissRouteImport.update({
  id: '/tiss',
  path: '/tiss',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessamentoRoute = ProcessamentoRouteImport.update({
  id: '/processamento',
  path: '/processamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantoesRoute = PlantoesRouteImport.update({
  id: '/plantoes',
  path: '/plantoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotoRoute = PilotoRouteImport.update({
  id: '/piloto',
  path: '/piloto',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacaoRoute = OperacaoRouteImport.update({
  id: '/operacao',
  path: '/operacao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentoRoute = LancamentoRouteImport.update({
  id: '/lancamento',
  path: '/lancamento',
  getParentRoute: () => rootRouteImport,
} as any)
const InstituicaoRoute = InstituicaoRouteImport.update({
  id: '/instituicao',
  path: '/instituicao',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutivoRoute = ExecutivoRouteImport.update({
  id: '/executivo',
  path: '/executivo',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalasRoute = EscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralRoute = CentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturaRoute = CapturaRouteImport.update({
  id: '/captura',
  path: '/captura',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantoesShiftIdRoute = PlantoesShiftIdRouteImport.update({
  id: '/$shiftId',
  path: '/$shiftId',
  getParentRoute: () => PlantoesRoute,
} as any)
const LoginRedefinirSenhaRoute = LoginRedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => LoginRoute,
} as any)
const LoginEsqueciSenhaRoute = LoginEsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => LoginRoute,
} as any)
const FinanceiroFechamentoOperacionalRoute =
  FinanceiroFechamentoOperacionalRouteImport.update({
    id: '/fechamento-operacional',
    path: '/fechamento-operacional',
    getParentRoute: () => FinanceiroRoute,
  } as any)
const FinanceiroDashboardExecutivoRoute =
  FinanceiroDashboardExecutivoRouteImport.update({
    id: '/dashboard-executivo',
    path: '/dashboard-executivo',
    getParentRoute: () => FinanceiroRoute,
  } as any)
const FinanceiroConciliacaoOperacionalRoute =
  FinanceiroConciliacaoOperacionalRouteImport.update({
    id: '/conciliacao-operacional',
    path: '/conciliacao-operacional',
    getParentRoute: () => FinanceiroRoute,
  } as any)
const Fase3SlugRoute = Fase3SlugRouteImport.update({
  id: '/fase3/$slug',
  path: '/fase3/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRevisaoContractIdRoute =
  ContratosRevisaoContractIdRouteImport.update({
    id: '/revisao/$contractId',
    path: '/revisao/$contractId',
    getParentRoute: () => ContratosRoute,
  } as any)
const CapturaRevisaoSessionIdRoute = CapturaRevisaoSessionIdRouteImport.update({
  id: '/revisao/$sessionId',
  path: '/revisao/$sessionId',
  getParentRoute: () => CapturaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/analytics': typeof AnalyticsRoute
  '/captura': typeof CapturaRouteWithChildren
  '/central': typeof CentralRoute
  '/contratos': typeof ContratosRouteWithChildren
  '/escalas': typeof EscalasRoute
  '/executivo': typeof ExecutivoRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/instituicao': typeof InstituicaoRoute
  '/lancamento': typeof LancamentoRoute
  '/login': typeof LoginRouteWithChildren
  '/operacao': typeof OperacaoRoute
  '/perfil': typeof PerfilRoute
  '/piloto': typeof PilotoRoute
  '/plantoes': typeof PlantoesRouteWithChildren
  '/processamento': typeof ProcessamentoRoute
  '/site': typeof SiteRoute
  '/tiss': typeof TissRoute
  '/fase3/$slug': typeof Fase3SlugRoute
  '/financeiro/conciliacao-operacional': typeof FinanceiroConciliacaoOperacionalRoute
  '/financeiro/dashboard-executivo': typeof FinanceiroDashboardExecutivoRoute
  '/financeiro/fechamento-operacional': typeof FinanceiroFechamentoOperacionalRoute
  '/login/esqueci-senha': typeof LoginEsqueciSenhaRoute
  '/login/redefinir-senha': typeof LoginRedefinirSenhaRoute
  '/plantoes/$shiftId': typeof PlantoesShiftIdRoute
  '/captura/revisao/$sessionId': typeof CapturaRevisaoSessionIdRoute
  '/contratos/revisao/$contractId': typeof ContratosRevisaoContractIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/analytics': typeof AnalyticsRoute
  '/captura': typeof CapturaRouteWithChildren
  '/central': typeof CentralRoute
  '/contratos': typeof ContratosRouteWithChildren
  '/escalas': typeof EscalasRoute
  '/executivo': typeof ExecutivoRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/instituicao': typeof InstituicaoRoute
  '/lancamento': typeof LancamentoRoute
  '/login': typeof LoginRouteWithChildren
  '/operacao': typeof OperacaoRoute
  '/perfil': typeof PerfilRoute
  '/piloto': typeof PilotoRoute
  '/plantoes': typeof PlantoesRouteWithChildren
  '/processamento': typeof ProcessamentoRoute
  '/site': typeof SiteRoute
  '/tiss': typeof TissRoute
  '/fase3/$slug': typeof Fase3SlugRoute
  '/financeiro/conciliacao-operacional': typeof FinanceiroConciliacaoOperacionalRoute
  '/financeiro/dashboard-executivo': typeof FinanceiroDashboardExecutivoRoute
  '/financeiro/fechamento-operacional': typeof FinanceiroFechamentoOperacionalRoute
  '/login/esqueci-senha': typeof LoginEsqueciSenhaRoute
  '/login/redefinir-senha': typeof LoginRedefinirSenhaRoute
  '/plantoes/$shiftId': typeof PlantoesShiftIdRoute
  '/captura/revisao/$sessionId': typeof CapturaRevisaoSessionIdRoute
  '/contratos/revisao/$contractId': typeof ContratosRevisaoContractIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/analytics': typeof AnalyticsRoute
  '/captura': typeof CapturaRouteWithChildren
  '/central': typeof CentralRoute
  '/contratos': typeof ContratosRouteWithChildren
  '/escalas': typeof EscalasRoute
  '/executivo': typeof ExecutivoRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/instituicao': typeof InstituicaoRoute
  '/lancamento': typeof LancamentoRoute
  '/login': typeof LoginRouteWithChildren
  '/operacao': typeof OperacaoRoute
  '/perfil': typeof PerfilRoute
  '/piloto': typeof PilotoRoute
  '/plantoes': typeof PlantoesRouteWithChildren
  '/processamento': typeof ProcessamentoRoute
  '/site': typeof SiteRoute
  '/tiss': typeof TissRoute
  '/fase3/$slug': typeof Fase3SlugRoute
  '/financeiro/conciliacao-operacional': typeof FinanceiroConciliacaoOperacionalRoute
  '/financeiro/dashboard-executivo': typeof FinanceiroDashboardExecutivoRoute
  '/financeiro/fechamento-operacional': typeof FinanceiroFechamentoOperacionalRoute
  '/login/esqueci-senha': typeof LoginEsqueciSenhaRoute
  '/login/redefinir-senha': typeof LoginRedefinirSenhaRoute
  '/plantoes/$shiftId': typeof PlantoesShiftIdRoute
  '/captura/revisao/$sessionId': typeof CapturaRevisaoSessionIdRoute
  '/contratos/revisao/$contractId': typeof ContratosRevisaoContractIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/analytics'
    | '/captura'
    | '/central'
    | '/contratos'
    | '/escalas'
    | '/executivo'
    | '/financeiro'
    | '/instituicao'
    | '/lancamento'
    | '/login'
    | '/operacao'
    | '/perfil'
    | '/piloto'
    | '/plantoes'
    | '/processamento'
    | '/site'
    | '/tiss'
    | '/fase3/$slug'
    | '/financeiro/conciliacao-operacional'
    | '/financeiro/dashboard-executivo'
    | '/financeiro/fechamento-operacional'
    | '/login/esqueci-senha'
    | '/login/redefinir-senha'
    | '/plantoes/$shiftId'
    | '/captura/revisao/$sessionId'
    | '/contratos/revisao/$contractId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/analytics'
    | '/captura'
    | '/central'
    | '/contratos'
    | '/escalas'
    | '/executivo'
    | '/financeiro'
    | '/instituicao'
    | '/lancamento'
    | '/login'
    | '/operacao'
    | '/perfil'
    | '/piloto'
    | '/plantoes'
    | '/processamento'
    | '/site'
    | '/tiss'
    | '/fase3/$slug'
    | '/financeiro/conciliacao-operacional'
    | '/financeiro/dashboard-executivo'
    | '/financeiro/fechamento-operacional'
    | '/login/esqueci-senha'
    | '/login/redefinir-senha'
    | '/plantoes/$shiftId'
    | '/captura/revisao/$sessionId'
    | '/contratos/revisao/$contractId'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/analytics'
    | '/captura'
    | '/central'
    | '/contratos'
    | '/escalas'
    | '/executivo'
    | '/financeiro'
    | '/instituicao'
    | '/lancamento'
    | '/login'
    | '/operacao'
    | '/perfil'
    | '/piloto'
    | '/plantoes'
    | '/processamento'
    | '/site'
    | '/tiss'
    | '/fase3/$slug'
    | '/financeiro/conciliacao-operacional'
    | '/financeiro/dashboard-executivo'
    | '/financeiro/fechamento-operacional'
    | '/login/esqueci-senha'
    | '/login/redefinir-senha'
    | '/plantoes/$shiftId'
    | '/captura/revisao/$sessionId'
    | '/contratos/revisao/$contractId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CapturaRoute: typeof CapturaRouteWithChildren
  CentralRoute: typeof CentralRoute
  ContratosRoute: typeof ContratosRouteWithChildren
  EscalasRoute: typeof EscalasRoute
  ExecutivoRoute: typeof ExecutivoRoute
  FinanceiroRoute: typeof FinanceiroRouteWithChildren
  InstituicaoRoute: typeof InstituicaoRoute
  LancamentoRoute: typeof LancamentoRoute
  LoginRoute: typeof LoginRouteWithChildren
  OperacaoRoute: typeof OperacaoRoute
  PerfilRoute: typeof PerfilRoute
  PilotoRoute: typeof PilotoRoute
  PlantoesRoute: typeof PlantoesRouteWithChildren
  ProcessamentoRoute: typeof ProcessamentoRoute
  SiteRoute: typeof SiteRoute
  TissRoute: typeof TissRoute
  Fase3SlugRoute: typeof Fase3SlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tiss': {
      id: '/tiss'
      path: '/tiss'
      fullPath: '/tiss'
      preLoaderRoute: typeof TissRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processamento': {
      id: '/processamento'
      path: '/processamento'
      fullPath: '/processamento'
      preLoaderRoute: typeof ProcessamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantoes': {
      id: '/plantoes'
      path: '/plantoes'
      fullPath: '/plantoes'
      preLoaderRoute: typeof PlantoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piloto': {
      id: '/piloto'
      path: '/piloto'
      fullPath: '/piloto'
      preLoaderRoute: typeof PilotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacao': {
      id: '/operacao'
      path: '/operacao'
      fullPath: '/operacao'
      preLoaderRoute: typeof OperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamento': {
      id: '/lancamento'
      path: '/lancamento'
      fullPath: '/lancamento'
      preLoaderRoute: typeof LancamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instituicao': {
      id: '/instituicao'
      path: '/instituicao'
      fullPath: '/instituicao'
      preLoaderRoute: typeof InstituicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executivo': {
      id: '/executivo'
      path: '/executivo'
      fullPath: '/executivo'
      preLoaderRoute: typeof ExecutivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalas': {
      id: '/escalas'
      path: '/escalas'
      fullPath: '/escalas'
      preLoaderRoute: typeof EscalasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central': {
      id: '/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof CentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captura': {
      id: '/captura'
      path: '/captura'
      fullPath: '/captura'
      preLoaderRoute: typeof CapturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantoes/$shiftId': {
      id: '/plantoes/$shiftId'
      path: '/$shiftId'
      fullPath: '/plantoes/$shiftId'
      preLoaderRoute: typeof PlantoesShiftIdRouteImport
      parentRoute: typeof PlantoesRoute
    }
    '/login/redefinir-senha': {
      id: '/login/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/login/redefinir-senha'
      preLoaderRoute: typeof LoginRedefinirSenhaRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/esqueci-senha': {
      id: '/login/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/login/esqueci-senha'
      preLoaderRoute: typeof LoginEsqueciSenhaRouteImport
      parentRoute: typeof LoginRoute
    }
    '/financeiro/fechamento-operacional': {
      id: '/financeiro/fechamento-operacional'
      path: '/fechamento-operacional'
      fullPath: '/financeiro/fechamento-operacional'
      preLoaderRoute: typeof FinanceiroFechamentoOperacionalRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/dashboard-executivo': {
      id: '/financeiro/dashboard-executivo'
      path: '/dashboard-executivo'
      fullPath: '/financeiro/dashboard-executivo'
      preLoaderRoute: typeof FinanceiroDashboardExecutivoRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/conciliacao-operacional': {
      id: '/financeiro/conciliacao-operacional'
      path: '/conciliacao-operacional'
      fullPath: '/financeiro/conciliacao-operacional'
      preLoaderRoute: typeof FinanceiroConciliacaoOperacionalRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/fase3/$slug': {
      id: '/fase3/$slug'
      path: '/fase3/$slug'
      fullPath: '/fase3/$slug'
      preLoaderRoute: typeof Fase3SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos/revisao/$contractId': {
      id: '/contratos/revisao/$contractId'
      path: '/revisao/$contractId'
      fullPath: '/contratos/revisao/$contractId'
      preLoaderRoute: typeof ContratosRevisaoContractIdRouteImport
      parentRoute: typeof ContratosRoute
    }
    '/captura/revisao/$sessionId': {
      id: '/captura/revisao/$sessionId'
      path: '/revisao/$sessionId'
      fullPath: '/captura/revisao/$sessionId'
      preLoaderRoute: typeof CapturaRevisaoSessionIdRouteImport
      parentRoute: typeof CapturaRoute
    }
  }
}

interface CapturaRouteChildren {
  CapturaRevisaoSessionIdRoute: typeof CapturaRevisaoSessionIdRoute
}

const CapturaRouteChildren: CapturaRouteChildren = {
  CapturaRevisaoSessionIdRoute: CapturaRevisaoSessionIdRoute,
}

const CapturaRouteWithChildren =
  CapturaRoute._addFileChildren(CapturaRouteChildren)

interface ContratosRouteChildren {
  ContratosRevisaoContractIdRoute: typeof ContratosRevisaoContractIdRoute
}

const ContratosRouteChildren: ContratosRouteChildren = {
  ContratosRevisaoContractIdRoute: ContratosRevisaoContractIdRoute,
}

const ContratosRouteWithChildren = ContratosRoute._addFileChildren(
  ContratosRouteChildren,
)

interface FinanceiroRouteChildren {
  FinanceiroConciliacaoOperacionalRoute: typeof FinanceiroConciliacaoOperacionalRoute
  FinanceiroDashboardExecutivoRoute: typeof FinanceiroDashboardExecutivoRoute
  FinanceiroFechamentoOperacionalRoute: typeof FinanceiroFechamentoOperacionalRoute
}

const FinanceiroRouteChildren: FinanceiroRouteChildren = {
  FinanceiroConciliacaoOperacionalRoute: FinanceiroConciliacaoOperacionalRoute,
  FinanceiroDashboardExecutivoRoute: FinanceiroDashboardExecutivoRoute,
  FinanceiroFechamentoOperacionalRoute: FinanceiroFechamentoOperacionalRoute,
}

const FinanceiroRouteWithChildren = FinanceiroRoute._addFileChildren(
  FinanceiroRouteChildren,
)

interface LoginRouteChildren {
  LoginEsqueciSenhaRoute: typeof LoginEsqueciSenhaRoute
  LoginRedefinirSenhaRoute: typeof LoginRedefinirSenhaRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginEsqueciSenhaRoute: LoginEsqueciSenhaRoute,
  LoginRedefinirSenhaRoute: LoginRedefinirSenhaRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface PlantoesRouteChildren {
  PlantoesShiftIdRoute: typeof PlantoesShiftIdRoute
}

const PlantoesRouteChildren: PlantoesRouteChildren = {
  PlantoesShiftIdRoute: PlantoesShiftIdRoute,
}

const PlantoesRouteWithChildren = PlantoesRoute._addFileChildren(
  PlantoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  AnalyticsRoute: AnalyticsRoute,
  CapturaRoute: CapturaRouteWithChildren,
  CentralRoute: CentralRoute,
  ContratosRoute: ContratosRouteWithChildren,
  EscalasRoute: EscalasRoute,
  ExecutivoRoute: ExecutivoRoute,
  FinanceiroRoute: FinanceiroRouteWithChildren,
  InstituicaoRoute: InstituicaoRoute,
  LancamentoRoute: LancamentoRoute,
  LoginRoute: LoginRouteWithChildren,
  OperacaoRoute: OperacaoRoute,
  PerfilRoute: PerfilRoute,
  PilotoRoute: PilotoRoute,
  PlantoesRoute: PlantoesRouteWithChildren,
  ProcessamentoRoute: ProcessamentoRoute,
  SiteRoute: SiteRoute,
  TissRoute: TissRoute,
  Fase3SlugRoute: Fase3SlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
