-- Estende operational_events_event_type_chk com os 2 novos event_type do
-- check-in/check-out de plantão (F4-S4) — mesma lista completa da última
-- vez que essa constraint foi redefinida (20250514100000), só com
-- 'assignment_checked_in'/'assignment_checked_out' adicionados ao final.
ALTER TABLE public.operational_events DROP CONSTRAINT IF EXISTS operational_events_event_type_chk;
ALTER TABLE public.operational_events ADD CONSTRAINT operational_events_event_type_chk CHECK (
  event_type IN (
    'shift_created',
    'shift_updated',
    'shift_cancelled',
    'assignment_created',
    'assignment_confirmed',
    'assignment_rejected',
    'assignment_checked_in',
    'assignment_checked_out',
    'swap_requested',
    'swap_approved',
    'swap_denied',
    'availability_updated',
    'critical_alert_generated',
    'operational_action_triggered',
    'orchestration_created',
    'orchestration_submitted_for_approval',
    'orchestration_approved',
    'orchestration_step_advanced',
    'orchestration_blocked',
    'orchestration_completed',
    'orchestration_rollback_previewed',
    'orchestration_rollback_step',
    'orchestration_rolled_back',
    'operational_agent_reasoning_cycle',
    'operational_agent_human_approved',
    'operational_agent_human_blocked',
    'operational_agent_unblocked',
    'operational_agent_coordination_cycle',
    'operational_memory_recorded',
    'operational_memory_state_updated',
    'operational_learning_signal_captured',
    'policy_intelligence_analysis_recorded',
    'policy_intelligence_cycle_state_updated',
    'policy_governance_recommendation_recorded',
    'policy_governance_recommendation_state_updated',
    'strategic_planning_cycle_recorded',
    'strategic_planning_cycle_state_updated',
    'strategic_planning_audit_appended',
    'tiss_guide_created',
    'tiss_guide_updated',
    'tiss_batch_closed',
    'tiss_batch_exported',
    'tiss_return_received',
    'tiss_return_processed',
    'tiss_denial_created',
    'tiss_denial_updated',
    'tiss_denial_reversed',
    'tiss_denial_appeal_created',
    'tiss_denial_appeal_updated',
    'medical_production_synced',
    'medical_payout_calculated',
    'medical_payout_reviewed',
    'medical_payout_approved',
    'medical_payout_paid',
    'medical_payout_status_changed',
    'payout_rule_created',
    'payout_rule_updated',
    'financial_closing_created',
    'financial_closing_consolidated',
    'financial_closing_status_changed',
    'financial_closing_locked',
    'financial_closing_unlocked',
    'financial_closing_snapshot_created',
    'financial_closing_finalized',
    'financial_closing_reopened',
    'operational_reconciliation_created',
    'operational_reconciliation_status_changed',
    'operational_reconciliation_matching_run',
    'operational_reconciliation_divergence_detected'
  )
);
