/**
 * Registro versionado de regras contratuais — dados seed por operadora.
 * MEDICFLOW-CONTRACT-INTELLIGENCE-01
 *
 * Suporta múltiplas versões por operadora e override por tenant (cliente).
 */
import type { ContractKnowledgeRegistry, ContractRule } from "../types/contract-rule";

const UNIMED_RULES_V1: ContractRule[] = [
  {
    ruleId: "CTR-UNI-001",
    operator: "123456",
    contract: "UNIMED-NACIONAL-2026",
    guideType: "*",
    procedureType: "*",
    priority: 100,
    description: "Registro ANS obrigatório para identificação da operadora",
    justification:
      "Contrato Unimed Nacional exige identificação inequívoca da operadora via registro ANS para processamento do lote.",
    legalReference: "RN 305/2012 ANS — Identificação da operadora",
    businessReference: "Manual Unimed Nacional v2026 — Cap. 3.1",
    severity: "critico",
    auditRuleIds: ["OPR-001"],
    auditFields: ["operator_ans_code"],
    baseDenialRisk: 95,
    estimatedFinancialImpactCents: 25000,
  },
  {
    ruleId: "CTR-UNI-002",
    operator: "123456",
    contract: "UNIMED-NACIONAL-2026",
    guideType: "guia_consulta",
    procedureType: "consulta",
    priority: 90,
    description: "Autorização prévia obrigatória para consultas eletivas",
    justification:
      "Consultas eletivas exigem senha de autorização válida conforme tabela de cobertura do contrato coletivo.",
    legalReference: "Lei 9.656/98 Art. 12 — Cobertura assistencial",
    businessReference: "Contrato Coletivo Unimed 2026 — Cláusula 7.3",
    severity: "alto",
    auditRuleIds: ["AUT-001", "AUT-002"],
    auditFields: ["authorization_password", "authorization_number"],
    baseDenialRisk: 80,
    estimatedFinancialImpactCents: 25000,
  },
  {
    ruleId: "CTR-UNI-003",
    operator: "123456",
    contract: "UNIMED-NACIONAL-2026",
    guideType: "guia_sadt",
    procedureType: "exame",
    priority: 85,
    description: "CID-10 obrigatório para procedimentos SP/SADT",
    justification:
      "Procedimentos diagnósticos requerem indicação clínica (CID-10) para validação de pertinência técnica.",
    legalReference: "RN 305/2012 — Dados de identificação do atendimento",
    businessReference: "Manual TISS 4.01.00 — Grupo diagnóstico",
    severity: "alto",
    auditRuleIds: ["DGN-001"],
    auditFields: ["cid_code"],
    baseDenialRisk: 70,
    estimatedFinancialImpactCents: 15000,
  },
  {
    ruleId: "CTR-UNI-004",
    operator: "123456",
    contract: "UNIMED-NACIONAL-2026",
    guideType: "*",
    procedureType: "*",
    priority: 80,
    description: "Código TUSS deve constar na tabela contratual vigente",
    justification:
      "Procedimentos fora da tabela contratual ou com código inválido são glosados integralmente.",
    legalReference: "RN 259/2011 ANS — Rol de procedimentos",
    businessReference: "Tabela TUSS Unimed 2026 — Anexo II",
    severity: "critico",
    auditRuleIds: ["PRC-001", "PRC-002"],
    auditFields: ["procedure_code"],
    baseDenialRisk: 90,
    estimatedFinancialImpactCents: 50000,
  },
  {
    ruleId: "CTR-UNI-005",
    operator: "123456",
    contract: "UNIMED-REGIONAL-2025",
    guideType: "guia_honorario",
    procedureType: "cirurgia",
    priority: 75,
    description: "Honorários cirúrgicos exigem equipe completa identificada",
    justification:
      "Guia de honorários deve conter CRM e nome de todos os profissionais participantes da equipe cirúrgica.",
    legalReference: "RN 305/2012 — Dados do executante",
    businessReference: "Contrato Regional Unimed 2025 — Cláusula 12.1",
    severity: "alto",
    auditRuleIds: ["EXE-001", "EXE-002"],
    auditFields: ["executor_crm", "executor_name"],
    baseDenialRisk: 65,
    estimatedFinancialImpactCents: 80000,
  },
];

const BRADESCO_RULES_V1: ContractRule[] = [
  {
    ruleId: "CTR-BRA-001",
    operator: "005711",
    contract: "BRADESCO-SAUDE-2026",
    guideType: "*",
    procedureType: "*",
    priority: 100,
    description: "Identificação da operadora via registro ANS Bradesco Saúde",
    justification:
      "Bradesco Saúde exige registro ANS 005711 para conciliação de lotes e validação de rede credenciada.",
    legalReference: "RN 305/2012 ANS",
    businessReference: "Manual Bradesco Saúde v2026 — Seção 2.1",
    severity: "critico",
    auditRuleIds: ["OPR-001", "OPR-002"],
    auditFields: ["operator_ans_code"],
    baseDenialRisk: 92,
    estimatedFinancialImpactCents: 30000,
  },
  {
    ruleId: "CTR-BRA-002",
    operator: "005711",
    contract: "BRADESCO-SAUDE-2026",
    guideType: "guia_sadt",
    procedureType: "*",
    priority: 90,
    description: "Autorização obrigatória para SP/SADT acima de R$ 500",
    justification:
      "Procedimentos SP/SADT com valor superior a R$ 500,00 exigem autorização prévia com senha válida.",
    legalReference: "Lei 9.656/98 Art. 12",
    businessReference: "Contrato Bradesco Empresarial 2026 — Anexo C",
    severity: "alto",
    auditRuleIds: ["AUT-001"],
    auditFields: ["authorization_password"],
    baseDenialRisk: 85,
    estimatedFinancialImpactCents: 50000,
  },
  {
    ruleId: "CTR-BRA-003",
    operator: "005711",
    contract: "BRADESCO-SAUDE-2026",
    guideType: "guia_consulta",
    procedureType: "consulta",
    priority: 70,
    description: "Carteirinha do beneficiário obrigatória",
    justification:
      "Identificação do beneficiário via número da carteirinha é requisito para elegibilidade no momento do atendimento.",
    legalReference: "RN 305/2012 — Dados do beneficiário",
    businessReference: "Manual Bradesco Saúde — Cap. 4.2",
    severity: "critico",
    auditRuleIds: ["PAC-002"],
    auditFields: ["beneficiary_card_number"],
    baseDenialRisk: 88,
    estimatedFinancialImpactCents: 25000,
  },
];

const AMIL_RULES_V1: ContractRule[] = [
  {
    ruleId: "CTR-AMI-001",
    operator: "326305",
    contract: "AMIL-ONE-2026",
    guideType: "*",
    procedureType: "*",
    priority: 100,
    description: "Registro ANS Amil obrigatório",
    justification: "Amil One exige identificação via ANS 326305 para processamento TISS.",
    legalReference: "RN 305/2012 ANS",
    businessReference: "Manual Amil One 2026",
    severity: "critico",
    auditRuleIds: ["OPR-001"],
    auditFields: ["operator_ans_code"],
    baseDenialRisk: 90,
    estimatedFinancialImpactCents: 25000,
  },
  {
    ruleId: "CTR-AMI-002",
    operator: "326305",
    contract: "AMIL-ONE-2026",
    guideType: "guia_sadt",
    procedureType: "exame",
    priority: 85,
    description: "Laudo/relatório obrigatório para exames de alta complexidade",
    justification:
      "Exames de alta complexidade exigem documentação complementar conforme rol ANS e contrato Amil.",
    legalReference: "RN 259/2011 ANS — Rol de procedimentos",
    businessReference: "Contrato Amil One — Cláusula 9.4",
    severity: "medio",
    auditCategories: ["procedimentos"],
    baseDenialRisk: 55,
    estimatedFinancialImpactCents: 12000,
  },
];

const SULAMERICA_RULES_V1: ContractRule[] = [
  {
    ruleId: "CTR-SUL-001",
    operator: "006246",
    contract: "SULAMERICA-2026",
    guideType: "*",
    procedureType: "*",
    priority: 100,
    description: "Identificação SulAmérica via ANS 006246",
    justification: "SulAmérica Saúde requer ANS 006246 para validação de rede e contrato.",
    legalReference: "RN 305/2012 ANS",
    businessReference: "Manual SulAmérica 2026 — Cap. 1",
    severity: "critico",
    auditRuleIds: ["OPR-001"],
    auditFields: ["operator_ans_code"],
    baseDenialRisk: 91,
    estimatedFinancialImpactCents: 28000,
  },
  {
    ruleId: "CTR-SUL-002",
    operator: "006246",
    contract: "SULAMERICA-2026",
    guideType: "guia_consulta",
    procedureType: "consulta",
    priority: 80,
    description: "Data de atendimento obrigatória para consultas",
    justification:
      "Consultas sem data de atendimento são rejeitadas no faturamento eletrônico SulAmérica.",
    legalReference: "RN 305/2012 — Datas do atendimento",
    businessReference: "Contrato SulAmérica 2026 — Cláusula 5.2",
    severity: "alto",
    auditRuleIds: ["DAT-001"],
    auditFields: ["attendance_date"],
    baseDenialRisk: 75,
    estimatedFinancialImpactCents: 25000,
  },
];

/** Regras genéricas ANS/TISS aplicáveis quando contrato não é identificado */
const GENERIC_RULES_V1: ContractRule[] = [
  {
    ruleId: "CTR-GEN-001",
    operator: "*",
    contract: "GENERIC-ANS",
    guideType: "*",
    procedureType: "*",
    priority: 50,
    description: "Registro ANS obrigatório (regra genérica ANS)",
    justification:
      "Toda guia TISS deve conter o registro ANS da operadora conforme padrão ANS/TISS.",
    legalReference: "RN 305/2012 ANS — Identificação da operadora",
    businessReference: "Padrão TISS 4.01.00 — Grupo operadora",
    severity: "critico",
    auditRuleIds: ["OPR-001"],
    auditFields: ["operator_ans_code"],
    baseDenialRisk: 85,
    estimatedFinancialImpactCents: 20000,
  },
  {
    ruleId: "CTR-GEN-002",
    operator: "*",
    contract: "GENERIC-ANS",
    guideType: "*",
    procedureType: "*",
    priority: 40,
    description: "Nome do beneficiário obrigatório (regra genérica TISS)",
    justification: "Identificação do beneficiário é campo obrigatório no padrão TISS.",
    legalReference: "RN 305/2012 — Dados do beneficiário",
    businessReference: "Padrão TISS 4.01.00 — Grupo beneficiário",
    severity: "critico",
    auditRuleIds: ["PAC-001"],
    auditFields: ["beneficiary_name"],
    baseDenialRisk: 80,
    estimatedFinancialImpactCents: 20000,
  },
  {
    ruleId: "CTR-GEN-003",
    operator: "*",
    contract: "GENERIC-ANS",
    guideType: "*",
    procedureType: "*",
    priority: 30,
    description: "Código de procedimento TUSS obrigatório",
    justification: "Procedimentos devem ser codificados conforme tabela TUSS vigente.",
    legalReference: "RN 259/2011 ANS — Rol de procedimentos",
    businessReference: "Padrão TISS 4.01.00 — Grupo procedimentos",
    severity: "critico",
    auditRuleIds: ["PRC-001"],
    auditFields: ["procedure_code"],
    baseDenialRisk: 88,
    estimatedFinancialImpactCents: 35000,
  },
];

/** Regra conflitante de menor prioridade — usada para teste de resolução */
const UNIMED_CONFLICT_RULE: ContractRule = {
  ruleId: "CTR-UNI-CONFLICT",
  operator: "123456",
  contract: "UNIMED-NACIONAL-2026",
  guideType: "guia_consulta",
  procedureType: "consulta",
  priority: 50,
  description: "[CONFLITO] Autorização opcional — versão antiga do contrato",
  justification: "Versão 2024 do contrato não exigia autorização para consultas.",
  legalReference: "Contrato Unimed 2024 (revogado)",
  businessReference: "Manual Unimed 2024 — Cap. 5 (obsoleto)",
  severity: "baixo",
  auditRuleIds: ["AUT-001"],
  auditFields: ["authorization_password"],
  baseDenialRisk: 20,
  estimatedFinancialImpactCents: 5000,
};

export const DEFAULT_CONTRACT_RULES: ContractRule[] = [
  ...UNIMED_RULES_V1,
  UNIMED_CONFLICT_RULE,
  ...BRADESCO_RULES_V1,
  ...AMIL_RULES_V1,
  ...SULAMERICA_RULES_V1,
  ...GENERIC_RULES_V1,
];

export const CONTRACT_RULE_COUNT = DEFAULT_CONTRACT_RULES.length;

export const DEFAULT_CONTRACT_REGISTRY: ContractKnowledgeRegistry = {
  registryVersion: "contract_registry_v1",
  updatedAt: "2026-07-06T00:00:00.000Z",
  versions: [
    {
      version: "2026.1",
      effectiveFrom: "2026-01-01",
      operator: "123456",
      contract: "UNIMED-NACIONAL-2026",
      rules: UNIMED_RULES_V1,
    },
    {
      version: "2025.2",
      effectiveFrom: "2025-06-01",
      effectiveTo: "2025-12-31",
      operator: "123456",
      contract: "UNIMED-REGIONAL-2025",
      rules: [UNIMED_RULES_V1[4]!],
    },
    {
      version: "2026.1",
      effectiveFrom: "2026-01-01",
      operator: "005711",
      contract: "BRADESCO-SAUDE-2026",
      rules: BRADESCO_RULES_V1,
    },
    {
      version: "2026.1",
      effectiveFrom: "2026-01-01",
      operator: "326305",
      contract: "AMIL-ONE-2026",
      rules: AMIL_RULES_V1,
    },
    {
      version: "2026.1",
      effectiveFrom: "2026-01-01",
      operator: "006246",
      contract: "SULAMERICA-2026",
      rules: SULAMERICA_RULES_V1,
    },
    {
      version: "2026.1",
      effectiveFrom: "2026-01-01",
      operator: "*",
      contract: "GENERIC-ANS",
      rules: GENERIC_RULES_V1,
    },
  ],
};
